recipe: default.v1
language: en
pipeline:
- name: SingleStepLLMCoGenFaF
  llm:
    model_group: gpt-4o-mini
  flow_retrieval: 
    active: false

policies:
- name: FlowPolicy
#  - name: EnterpriseSearchPolicy
assistant_id: 20250316-212815-white-null
